---
version: '3'
services:

  # Raspberry Pi CSI camera
  prusa-connect-cam-rpi-csi:
    image: quay.io/kaszpir/prusa-connect-script
    read_only: true
    restart: unless-stopped
    env_file:
    - .docker-csi # copy docker-csi.dist as .docker-csi and adjust env vars
    devices:
    - /dev:/dev
    volumes:
    - /dev/:/dev/
    - /run/udev:/run/udev:ro
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 32MB

  # generic camera available as /dev/video0
  prusa-connect-cam-usb:
    image: quay.io/kaszpir/prusa-connect-script
    read_only: true
    restart: unless-stopped
    env_file:
    - .docker-video0 # copy docker-video0.dist as .docker-video0 and adjust env vars
    devices:
    - /dev:/dev
    volumes:
    - /dev/:/dev/
    - /run/udev:/run/udev:ro
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 32MB

  # esp32 snapshot
  prusa-connect-cam-rpi-esp-snapshot:
    image: quay.io/kaszpir/prusa-connect-script
    read_only: true
    restart: unless-stopped
    env_file:
    - .docker-esphome-snapshot # copy docker-esphome-snapshot.dist as .docker-esphome-snapshot and adjust env vars
    volumes:
    - type: tmpfs
      target: /dev/shm
      tmpfs:
        size: 32MB
